packages:
  - 'apps/*'
  - 'packages/*'

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - 'expo@57.0.2'
  - 'expo-router@57.0.8'
  - 'expo-camera@57.0.3'
  - 'expo-constants@57.0.11'
  - 'expo-linking@57.0.4'
  - 'expo-location@57.0.11'
  - 'expo-sensors@57.0.2'

allowBuilds:
  '@swc/core': true
