import { readFileSync } from 'node:fs';
import path from 'node:path';

export const SKY_IMAGE_SERVICE_ORIGIN =
  'https://alasky.cds.unistra.fr' as const;

export const PAN_STARRS_COLOR_SURVEY_ID =
  'CDS/P/PanSTARRS/DR1/color-i-r-g' as const;
export const ALL_WISE_COLOR_SURVEY_ID = 'CDS/P/allWISE/color' as const;

type DsoSurveyId =
  typeof PAN_STARRS_COLOR_SURVEY_ID | typeof ALL_WISE_COLOR_SURVEY_ID;

interface ImageCatalogueTarget {
  declinationJ2000Degrees: number;
  id: string;
  majorAxisArcminutes?: number;
  memberships: {
    caldwell?: number;
    messier: number[];
  };
  minorAxisArcminutes?: number;
  objectType: string;
  preferredName: string;
  prominenceTier: 1 | 2 | 3 | 4;
  rightAscensionJ2000Hours: number;
}

interface ImageCatalogue {
  targets: ImageCatalogueTarget[];
}

export interface DsoImageRequest {
  declinationJ2000Degrees: number;
  fieldOfViewDegrees: number;
  heightPixels: 256;
  rightAscensionJ2000Hours: number;
  surveyId: DsoSurveyId;
  targetId: string;
  widthPixels: 256;
}

const namedDsoObjectTypes = new Set([
  '*Ass',
  'Cl+N',
  'DrkN',
  'G',
  'GCl',
  'GGroup',
  'GPair',
  'HII',
  'Neb',
  'OCl',
  'PN',
  'RfN',
  'SNR',
]);

const displayCatalogueName = (value: string) => {
  const match = /^(NGC|IC|M|C)(\d+)(.*)$/.exec(value);
  if (!match) return value.replace(/\s+/g, ' ').trim();
  return `${match[1]} ${Number(match[2])}${match[3]}`.trim();
};

const isRequiredImageTarget = (target: ImageCatalogueTarget) =>
  target.memberships.messier.length > 0 ||
  target.memberships.caldwell !== undefined ||
  (target.prominenceTier === 1 &&
    namedDsoObjectTypes.has(target.objectType) &&
    target.preferredName !== displayCatalogueName(target.id));

const clamp = (value: number, minimum: number, maximum: number) =>
  Math.max(minimum, Math.min(maximum, value));

const fieldOfViewForTarget = (target: ImageCatalogueTarget) => {
  const finiteDimensionsArcminutes = [
    target.majorAxisArcminutes,
    target.minorAxisArcminutes,
  ].filter(
    (dimensionArcminutes): dimensionArcminutes is number =>
      dimensionArcminutes !== undefined &&
      Number.isFinite(dimensionArcminutes) &&
      dimensionArcminutes > 0,
  );
  if (finiteDimensionsArcminutes.length === 0) return 2.5;
  const largestDimensionDegrees = Math.max(...finiteDimensionsArcminutes) / 60;
  return Number(clamp(largestDimensionDegrees * 1.25, 0.25, 12).toFixed(3));
};

const surveyForTarget = (
  target: ImageCatalogueTarget,
  fieldOfViewDegrees: number,
): DsoSurveyId =>
  target.declinationJ2000Degrees - fieldOfViewDegrees / 2 >= -30
    ? PAN_STARRS_COLOR_SURVEY_ID
    : ALL_WISE_COLOR_SURVEY_ID;

export const buildDsoImageRequests = (
  catalogue: ImageCatalogue,
): readonly DsoImageRequest[] =>
  catalogue.targets
    .filter(isRequiredImageTarget)
    .map((target) => {
      const fieldOfViewDegrees = fieldOfViewForTarget(target);
      return {
        targetId: target.id,
        rightAscensionJ2000Hours: target.rightAscensionJ2000Hours,
        declinationJ2000Degrees: target.declinationJ2000Degrees,
        fieldOfViewDegrees,
        widthPixels: 256 as const,
        heightPixels: 256 as const,
        surveyId: surveyForTarget(target, fieldOfViewDegrees),
      };
    })
    .sort((left, right) => left.targetId.localeCompare(right.targetId, 'en'));

export const assetFileNameForTargetId = (targetId: string) => {
  const fileName = targetId.replace(/[^A-Za-z0-9_-]/g, '-');
  if (!fileName) throw new TypeError('DSO target ID has no safe filename');
  return fileName;
};

export const createRegisteredSkyAssetsModule = (
  requests: readonly DsoImageRequest[],
) => {
  const usedFileNames = new Set<string>();
  const imports = requests.map((request, index) => {
    const fileName = assetFileNameForTargetId(request.targetId);
    if (usedFileNames.has(fileName)) {
      throw new TypeError(`Duplicate DSO asset filename: ${fileName}`);
    }
    usedFileNames.add(fileName);
    const importName = `dsoImage${String(index).padStart(3, '0')}`;
    return `import ${importName} from '../../assets/sky/dso/${fileName}.jpg';`;
  });
  const mappings = requests.map((request, index) => {
    const importName = `dsoImage${String(index).padStart(3, '0')}`;
    const targetId = request.targetId
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'");
    const targetKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(targetId)
      ? targetId
      : `'${targetId}'`;
    return `  ${targetKey}: ${importName},`;
  });
  return [
    '// Generated by scripts/sky-assets/generateSkyAssets.ts. Do not edit.',
    "import milkyWayAtlasImage from '../../assets/sky/stellarium-milkyway.png';",
    ...imports,
    '',
    'export { milkyWayAtlasImage };',
    '',
    'export const dsoImageAssets: Readonly<Record<string, number>> = {',
    ...mappings,
    '};',
    '',
  ].join('\n');
};

const mobileDirectory = process
  .cwd()
  .endsWith(`${path.sep}apps${path.sep}mobile`)
  ? process.cwd()
  : path.resolve(process.cwd(), 'apps/mobile');
const catalogue = JSON.parse(
  readFileSync(
    path.join(mobileDirectory, 'src/catalogue/generated/catalogue.json'),
    'utf8',
  ),
) as ImageCatalogue;

export const milkyWayAtlasRequest = {
  fileName: 'stellarium-milkyway.png',
  heightPixels: 1024,
  sourceUrl:
    'https://raw.githubusercontent.com/Stellarium/stellarium/e6d38fe5e71e2c591c975fb068f2daf0b89d59b0/textures/milkyway.png',
  widthPixels: 2048,
} as const;

export const dsoImageRequests = buildDsoImageRequests(catalogue);

export const createHips2FitsUrl = (query: Record<string, string>): URL => {
  const url = new URL(
    '/hips-image-services/hips2fits',
    SKY_IMAGE_SERVICE_ORIGIN,
  );
  for (const [key, value] of Object.entries(query)) {
    url.searchParams.set(key, value);
  }
  return url;
};

export const createDsoImageUrl = (request: DsoImageRequest): URL =>
  createHips2FitsUrl({
    coordsys: 'icrs',
    dec: String(request.declinationJ2000Degrees),
    format: 'jpg',
    fov: String(request.fieldOfViewDegrees),
    height: String(request.heightPixels),
    hips: request.surveyId,
    inverse_longitude: 'false',
    projection: 'TAN',
    ra: String(request.rightAscensionJ2000Hours * 15),
    width: String(request.widthPixels),
  });
