// Generated by scripts/sky-assets/generateSkyAssets.ts. Do not edit.
import gaiaAtlasImage from '../../assets/sky/gaia-dr3-flux-color-car.jpg';
import dsoImage000 from '../../assets/sky/dso/B033.jpg';
import dsoImage001 from '../../assets/sky/dso/C009.jpg';
import dsoImage002 from '../../assets/sky/dso/C014.jpg';
import dsoImage003 from '../../assets/sky/dso/C041.jpg';
import dsoImage004 from '../../assets/sky/dso/C099.jpg';
import dsoImage005 from '../../assets/sky/dso/Cl399.jpg';
import dsoImage006 from '../../assets/sky/dso/ESO056-115.jpg';
import dsoImage007 from '../../assets/sky/dso/ESO097-013.jpg';
import dsoImage008 from '../../assets/sky/dso/ESO270-017.jpg';
import dsoImage009 from '../../assets/sky/dso/ESO351-030.jpg';
import dsoImage010 from '../../assets/sky/dso/ESO356-004.jpg';
import dsoImage011 from '../../assets/sky/dso/HCG079.jpg';
import dsoImage012 from '../../assets/sky/dso/HCG092.jpg';
import dsoImage013 from '../../assets/sky/dso/IC0342.jpg';
import dsoImage014 from '../../assets/sky/dso/IC0348.jpg';
import dsoImage015 from '../../assets/sky/dso/IC0349.jpg';
import dsoImage016 from '../../assets/sky/dso/IC0405.jpg';
import dsoImage017 from '../../assets/sky/dso/IC0434.jpg';
import dsoImage018 from '../../assets/sky/dso/IC0443.jpg';
import dsoImage019 from '../../assets/sky/dso/IC1613.jpg';
import dsoImage020 from '../../assets/sky/dso/IC2220.jpg';
import dsoImage021 from '../../assets/sky/dso/IC2391.jpg';
import dsoImage022 from '../../assets/sky/dso/IC2431-NED02.jpg';
import dsoImage023 from '../../assets/sky/dso/IC2574.jpg';
import dsoImage024 from '../../assets/sky/dso/IC2602.jpg';
import dsoImage025 from '../../assets/sky/dso/IC2944.jpg';
import dsoImage026 from '../../assets/sky/dso/IC4604.jpg';
import dsoImage027 from '../../assets/sky/dso/IC4703.jpg';
import dsoImage028 from '../../assets/sky/dso/IC4715.jpg';
import dsoImage029 from '../../assets/sky/dso/IC4725.jpg';
import dsoImage030 from '../../assets/sky/dso/IC5070.jpg';
import dsoImage031 from '../../assets/sky/dso/IC5146.jpg';
import dsoImage032 from '../../assets/sky/dso/M040.jpg';
import dsoImage033 from '../../assets/sky/dso/Mel022.jpg';
import dsoImage034 from '../../assets/sky/dso/Mel111.jpg';
import dsoImage035 from '../../assets/sky/dso/NGC0040.jpg';
import dsoImage036 from '../../assets/sky/dso/NGC0055.jpg';
import dsoImage037 from '../../assets/sky/dso/NGC0104.jpg';
import dsoImage038 from '../../assets/sky/dso/NGC0147.jpg';
import dsoImage039 from '../../assets/sky/dso/NGC0185.jpg';
import dsoImage040 from '../../assets/sky/dso/NGC0188.jpg';
import dsoImage041 from '../../assets/sky/dso/NGC0205.jpg';
import dsoImage042 from '../../assets/sky/dso/NGC0221.jpg';
import dsoImage043 from '../../assets/sky/dso/NGC0224.jpg';
import dsoImage044 from '../../assets/sky/dso/NGC0246.jpg';
import dsoImage045 from '../../assets/sky/dso/NGC0247.jpg';
import dsoImage046 from '../../assets/sky/dso/NGC0253.jpg';
import dsoImage047 from '../../assets/sky/dso/NGC0292.jpg';
import dsoImage048 from '../../assets/sky/dso/NGC0300.jpg';
import dsoImage049 from '../../assets/sky/dso/NGC0362.jpg';
import dsoImage050 from '../../assets/sky/dso/NGC0457.jpg';
import dsoImage051 from '../../assets/sky/dso/NGC0559.jpg';
import dsoImage052 from '../../assets/sky/dso/NGC0581.jpg';
import dsoImage053 from '../../assets/sky/dso/NGC0598.jpg';
import dsoImage054 from '../../assets/sky/dso/NGC0628.jpg';
import dsoImage055 from '../../assets/sky/dso/NGC0650.jpg';
import dsoImage056 from '../../assets/sky/dso/NGC0663.jpg';
import dsoImage057 from '../../assets/sky/dso/NGC0752.jpg';
import dsoImage058 from '../../assets/sky/dso/NGC0869.jpg';
import dsoImage059 from '../../assets/sky/dso/NGC0884.jpg';
import dsoImage060 from '../../assets/sky/dso/NGC0891.jpg';
import dsoImage061 from '../../assets/sky/dso/NGC1039.jpg';
import dsoImage062 from '../../assets/sky/dso/NGC1049.jpg';
import dsoImage063 from '../../assets/sky/dso/NGC1068.jpg';
import dsoImage064 from '../../assets/sky/dso/NGC1097.jpg';
import dsoImage065 from '../../assets/sky/dso/NGC1261.jpg';
import dsoImage066 from '../../assets/sky/dso/NGC1275.jpg';
import dsoImage067 from '../../assets/sky/dso/NGC1316.jpg';
import dsoImage068 from '../../assets/sky/dso/NGC1317.jpg';
import dsoImage069 from '../../assets/sky/dso/NGC1432.jpg';
import dsoImage070 from '../../assets/sky/dso/NGC1435.jpg';
import dsoImage071 from '../../assets/sky/dso/NGC1499.jpg';
import dsoImage072 from '../../assets/sky/dso/NGC1555.jpg';
import dsoImage073 from '../../assets/sky/dso/NGC1851.jpg';
import dsoImage074 from '../../assets/sky/dso/NGC1904.jpg';
import dsoImage075 from '../../assets/sky/dso/NGC1909.jpg';
import dsoImage076 from '../../assets/sky/dso/NGC1912.jpg';
import dsoImage077 from '../../assets/sky/dso/NGC1952.jpg';
import dsoImage078 from '../../assets/sky/dso/NGC1960.jpg';
import dsoImage079 from '../../assets/sky/dso/NGC1976.jpg';
import dsoImage080 from '../../assets/sky/dso/NGC1977.jpg';
import dsoImage081 from '../../assets/sky/dso/NGC1980.jpg';
import dsoImage082 from '../../assets/sky/dso/NGC1981.jpg';
import dsoImage083 from '../../assets/sky/dso/NGC1982.jpg';
import dsoImage084 from '../../assets/sky/dso/NGC2068.jpg';
import dsoImage085 from '../../assets/sky/dso/NGC2070.jpg';
import dsoImage086 from '../../assets/sky/dso/NGC2099.jpg';
import dsoImage087 from '../../assets/sky/dso/NGC2168.jpg';
import dsoImage088 from '../../assets/sky/dso/NGC2174.jpg';
import dsoImage089 from '../../assets/sky/dso/NGC2237.jpg';
import dsoImage090 from '../../assets/sky/dso/NGC2238.jpg';
import dsoImage091 from '../../assets/sky/dso/NGC2239.jpg';
import dsoImage092 from '../../assets/sky/dso/NGC2246.jpg';
import dsoImage093 from '../../assets/sky/dso/NGC2261.jpg';
import dsoImage094 from '../../assets/sky/dso/NGC2264.jpg';
import dsoImage095 from '../../assets/sky/dso/NGC2287.jpg';
import dsoImage096 from '../../assets/sky/dso/NGC2301.jpg';
import dsoImage097 from '../../assets/sky/dso/NGC2323.jpg';
import dsoImage098 from '../../assets/sky/dso/NGC2360.jpg';
import dsoImage099 from '../../assets/sky/dso/NGC2362.jpg';
import dsoImage100 from '../../assets/sky/dso/NGC2392.jpg';
import dsoImage101 from '../../assets/sky/dso/NGC2403.jpg';
import dsoImage102 from '../../assets/sky/dso/NGC2419.jpg';
import dsoImage103 from '../../assets/sky/dso/NGC2422.jpg';
import dsoImage104 from '../../assets/sky/dso/NGC2437.jpg';
import dsoImage105 from '../../assets/sky/dso/NGC2447.jpg';
import dsoImage106 from '../../assets/sky/dso/NGC2477.jpg';
import dsoImage107 from '../../assets/sky/dso/NGC2506.jpg';
import dsoImage108 from '../../assets/sky/dso/NGC2516.jpg';
import dsoImage109 from '../../assets/sky/dso/NGC2537.jpg';
import dsoImage110 from '../../assets/sky/dso/NGC2548.jpg';
import dsoImage111 from '../../assets/sky/dso/NGC2573.jpg';
import dsoImage112 from '../../assets/sky/dso/NGC2632.jpg';
import dsoImage113 from '../../assets/sky/dso/NGC2682.jpg';
import dsoImage114 from '../../assets/sky/dso/NGC2685.jpg';
import dsoImage115 from '../../assets/sky/dso/NGC2736.jpg';
import dsoImage116 from '../../assets/sky/dso/NGC2775.jpg';
import dsoImage117 from '../../assets/sky/dso/NGC2867.jpg';
import dsoImage118 from '../../assets/sky/dso/NGC3031.jpg';
import dsoImage119 from '../../assets/sky/dso/NGC3034.jpg';
import dsoImage120 from '../../assets/sky/dso/NGC3115.jpg';
import dsoImage121 from '../../assets/sky/dso/NGC3132.jpg';
import dsoImage122 from '../../assets/sky/dso/NGC3172.jpg';
import dsoImage123 from '../../assets/sky/dso/NGC3195.jpg';
import dsoImage124 from '../../assets/sky/dso/NGC3201.jpg';
import dsoImage125 from '../../assets/sky/dso/NGC3242.jpg';
import dsoImage126 from '../../assets/sky/dso/NGC3351.jpg';
import dsoImage127 from '../../assets/sky/dso/NGC3368.jpg';
import dsoImage128 from '../../assets/sky/dso/NGC3372.jpg';
import dsoImage129 from '../../assets/sky/dso/NGC3379.jpg';
import dsoImage130 from '../../assets/sky/dso/NGC3532.jpg';
import dsoImage131 from '../../assets/sky/dso/NGC3556.jpg';
import dsoImage132 from '../../assets/sky/dso/NGC3561.jpg';
import dsoImage133 from '../../assets/sky/dso/NGC3587.jpg';
import dsoImage134 from '../../assets/sky/dso/NGC3623.jpg';
import dsoImage135 from '../../assets/sky/dso/NGC3626.jpg';
import dsoImage136 from '../../assets/sky/dso/NGC3627.jpg';
import dsoImage137 from '../../assets/sky/dso/NGC3766.jpg';
import dsoImage138 from '../../assets/sky/dso/NGC3918.jpg';
import dsoImage139 from '../../assets/sky/dso/NGC3928.jpg';
import dsoImage140 from '../../assets/sky/dso/NGC3992.jpg';
import dsoImage141 from '../../assets/sky/dso/NGC4038.jpg';
import dsoImage142 from '../../assets/sky/dso/NGC4039.jpg';
import dsoImage143 from '../../assets/sky/dso/NGC4192.jpg';
import dsoImage144 from '../../assets/sky/dso/NGC4194.jpg';
import dsoImage145 from '../../assets/sky/dso/NGC4236.jpg';
import dsoImage146 from '../../assets/sky/dso/NGC4244.jpg';
import dsoImage147 from '../../assets/sky/dso/NGC4254.jpg';
import dsoImage148 from '../../assets/sky/dso/NGC4258.jpg';
import dsoImage149 from '../../assets/sky/dso/NGC4303.jpg';
import dsoImage150 from '../../assets/sky/dso/NGC4321.jpg';
import dsoImage151 from '../../assets/sky/dso/NGC4372.jpg';
import dsoImage152 from '../../assets/sky/dso/NGC4374.jpg';
import dsoImage153 from '../../assets/sky/dso/NGC4382.jpg';
import dsoImage154 from '../../assets/sky/dso/NGC4406.jpg';
import dsoImage155 from '../../assets/sky/dso/NGC4435.jpg';
import dsoImage156 from '../../assets/sky/dso/NGC4438.jpg';
import dsoImage157 from '../../assets/sky/dso/NGC4449.jpg';
import dsoImage158 from '../../assets/sky/dso/NGC4472.jpg';
import dsoImage159 from '../../assets/sky/dso/NGC4486.jpg';
import dsoImage160 from '../../assets/sky/dso/NGC4501.jpg';
import dsoImage161 from '../../assets/sky/dso/NGC4548.jpg';
import dsoImage162 from '../../assets/sky/dso/NGC4552.jpg';
import dsoImage163 from '../../assets/sky/dso/NGC4559.jpg';
import dsoImage164 from '../../assets/sky/dso/NGC4565.jpg';
import dsoImage165 from '../../assets/sky/dso/NGC4567.jpg';
import dsoImage166 from '../../assets/sky/dso/NGC4568.jpg';
import dsoImage167 from '../../assets/sky/dso/NGC4569.jpg';
import dsoImage168 from '../../assets/sky/dso/NGC4579.jpg';
import dsoImage169 from '../../assets/sky/dso/NGC4590.jpg';
import dsoImage170 from '../../assets/sky/dso/NGC4594.jpg';
import dsoImage171 from '../../assets/sky/dso/NGC4609.jpg';
import dsoImage172 from '../../assets/sky/dso/NGC4621.jpg';
import dsoImage173 from '../../assets/sky/dso/NGC4631.jpg';
import dsoImage174 from '../../assets/sky/dso/NGC4649.jpg';
import dsoImage175 from '../../assets/sky/dso/NGC4651.jpg';
import dsoImage176 from '../../assets/sky/dso/NGC4676.jpg';
import dsoImage177 from '../../assets/sky/dso/NGC4697.jpg';
import dsoImage178 from '../../assets/sky/dso/NGC4736.jpg';
import dsoImage179 from '../../assets/sky/dso/NGC4755.jpg';
import dsoImage180 from '../../assets/sky/dso/NGC4826.jpg';
import dsoImage181 from '../../assets/sky/dso/NGC4833.jpg';
import dsoImage182 from '../../assets/sky/dso/NGC4889.jpg';
import dsoImage183 from '../../assets/sky/dso/NGC4945.jpg';
import dsoImage184 from '../../assets/sky/dso/NGC4990.jpg';
import dsoImage185 from '../../assets/sky/dso/NGC5005.jpg';
import dsoImage186 from '../../assets/sky/dso/NGC5024.jpg';
import dsoImage187 from '../../assets/sky/dso/NGC5055.jpg';
import dsoImage188 from '../../assets/sky/dso/NGC5128.jpg';
import dsoImage189 from '../../assets/sky/dso/NGC5139.jpg';
import dsoImage190 from '../../assets/sky/dso/NGC5194.jpg';
import dsoImage191 from '../../assets/sky/dso/NGC5236.jpg';
import dsoImage192 from '../../assets/sky/dso/NGC5248.jpg';
import dsoImage193 from '../../assets/sky/dso/NGC5272.jpg';
import dsoImage194 from '../../assets/sky/dso/NGC5286.jpg';
import dsoImage195 from '../../assets/sky/dso/NGC5457.jpg';
import dsoImage196 from '../../assets/sky/dso/NGC5694.jpg';
import dsoImage197 from '../../assets/sky/dso/NGC5823.jpg';
import dsoImage198 from '../../assets/sky/dso/NGC5904.jpg';
import dsoImage199 from '../../assets/sky/dso/NGC6025.jpg';
import dsoImage200 from '../../assets/sky/dso/NGC6087.jpg';
import dsoImage201 from '../../assets/sky/dso/NGC6093.jpg';
import dsoImage202 from '../../assets/sky/dso/NGC6101.jpg';
import dsoImage203 from '../../assets/sky/dso/NGC6121.jpg';
import dsoImage204 from '../../assets/sky/dso/NGC6124.jpg';
import dsoImage205 from '../../assets/sky/dso/NGC6171.jpg';
import dsoImage206 from '../../assets/sky/dso/NGC6188.jpg';
import dsoImage207 from '../../assets/sky/dso/NGC6193.jpg';
import dsoImage208 from '../../assets/sky/dso/NGC6205.jpg';
import dsoImage209 from '../../assets/sky/dso/NGC6218.jpg';
import dsoImage210 from '../../assets/sky/dso/NGC6231.jpg';
import dsoImage211 from '../../assets/sky/dso/NGC6254.jpg';
import dsoImage212 from '../../assets/sky/dso/NGC6266.jpg';
import dsoImage213 from '../../assets/sky/dso/NGC6273.jpg';
import dsoImage214 from '../../assets/sky/dso/NGC6302.jpg';
import dsoImage215 from '../../assets/sky/dso/NGC6309.jpg';
import dsoImage216 from '../../assets/sky/dso/NGC6333.jpg';
import dsoImage217 from '../../assets/sky/dso/NGC6341.jpg';
import dsoImage218 from '../../assets/sky/dso/NGC6352.jpg';
import dsoImage219 from '../../assets/sky/dso/NGC6357.jpg';
import dsoImage220 from '../../assets/sky/dso/NGC6369.jpg';
import dsoImage221 from '../../assets/sky/dso/NGC6397.jpg';
import dsoImage222 from '../../assets/sky/dso/NGC6402.jpg';
import dsoImage223 from '../../assets/sky/dso/NGC6405.jpg';
import dsoImage224 from '../../assets/sky/dso/NGC6445.jpg';
import dsoImage225 from '../../assets/sky/dso/NGC6475.jpg';
import dsoImage226 from '../../assets/sky/dso/NGC6494.jpg';
import dsoImage227 from '../../assets/sky/dso/NGC6514.jpg';
import dsoImage228 from '../../assets/sky/dso/NGC6523.jpg';
import dsoImage229 from '../../assets/sky/dso/NGC6531.jpg';
import dsoImage230 from '../../assets/sky/dso/NGC6537.jpg';
import dsoImage231 from '../../assets/sky/dso/NGC6541.jpg';
import dsoImage232 from '../../assets/sky/dso/NGC6543.jpg';
import dsoImage233 from '../../assets/sky/dso/NGC6611.jpg';
import dsoImage234 from '../../assets/sky/dso/NGC6613.jpg';
import dsoImage235 from '../../assets/sky/dso/NGC6618.jpg';
import dsoImage236 from '../../assets/sky/dso/NGC6626.jpg';
import dsoImage237 from '../../assets/sky/dso/NGC6637.jpg';
import dsoImage238 from '../../assets/sky/dso/NGC6656.jpg';
import dsoImage239 from '../../assets/sky/dso/NGC6681.jpg';
import dsoImage240 from '../../assets/sky/dso/NGC6694.jpg';
import dsoImage241 from '../../assets/sky/dso/NGC6705.jpg';
import dsoImage242 from '../../assets/sky/dso/NGC6715.jpg';
import dsoImage243 from '../../assets/sky/dso/NGC6720.jpg';
import dsoImage244 from '../../assets/sky/dso/NGC6729.jpg';
import dsoImage245 from '../../assets/sky/dso/NGC6741.jpg';
import dsoImage246 from '../../assets/sky/dso/NGC6744.jpg';
import dsoImage247 from '../../assets/sky/dso/NGC6752.jpg';
import dsoImage248 from '../../assets/sky/dso/NGC6779.jpg';
import dsoImage249 from '../../assets/sky/dso/NGC6809.jpg';
import dsoImage250 from '../../assets/sky/dso/NGC6818.jpg';
import dsoImage251 from '../../assets/sky/dso/NGC6819.jpg';
import dsoImage252 from '../../assets/sky/dso/NGC6822.jpg';
import dsoImage253 from '../../assets/sky/dso/NGC6826.jpg';
import dsoImage254 from '../../assets/sky/dso/NGC6838.jpg';
import dsoImage255 from '../../assets/sky/dso/NGC6853.jpg';
import dsoImage256 from '../../assets/sky/dso/NGC6864.jpg';
import dsoImage257 from '../../assets/sky/dso/NGC6882.jpg';
import dsoImage258 from '../../assets/sky/dso/NGC6888.jpg';
import dsoImage259 from '../../assets/sky/dso/NGC6905.jpg';
import dsoImage260 from '../../assets/sky/dso/NGC6913.jpg';
import dsoImage261 from '../../assets/sky/dso/NGC6934.jpg';
import dsoImage262 from '../../assets/sky/dso/NGC6946.jpg';
import dsoImage263 from '../../assets/sky/dso/NGC6960.jpg';
import dsoImage264 from '../../assets/sky/dso/NGC6981.jpg';
import dsoImage265 from '../../assets/sky/dso/NGC6992.jpg';
import dsoImage266 from '../../assets/sky/dso/NGC6994.jpg';
import dsoImage267 from '../../assets/sky/dso/NGC6995.jpg';
import dsoImage268 from '../../assets/sky/dso/NGC7000.jpg';
import dsoImage269 from '../../assets/sky/dso/NGC7006.jpg';
import dsoImage270 from '../../assets/sky/dso/NGC7009.jpg';
import dsoImage271 from '../../assets/sky/dso/NGC7023.jpg';
import dsoImage272 from '../../assets/sky/dso/NGC7078.jpg';
import dsoImage273 from '../../assets/sky/dso/NGC7089.jpg';
import dsoImage274 from '../../assets/sky/dso/NGC7092.jpg';
import dsoImage275 from '../../assets/sky/dso/NGC7099.jpg';
import dsoImage276 from '../../assets/sky/dso/NGC7243.jpg';
import dsoImage277 from '../../assets/sky/dso/NGC7293.jpg';
import dsoImage278 from '../../assets/sky/dso/NGC7331.jpg';
import dsoImage279 from '../../assets/sky/dso/NGC7479.jpg';
import dsoImage280 from '../../assets/sky/dso/NGC7635.jpg';
import dsoImage281 from '../../assets/sky/dso/NGC7654.jpg';
import dsoImage282 from '../../assets/sky/dso/NGC7662.jpg';
import dsoImage283 from '../../assets/sky/dso/NGC7814.jpg';
import dsoImage284 from '../../assets/sky/dso/PGC000143.jpg';
import dsoImage285 from '../../assets/sky/dso/PGC029653.jpg';
import dsoImage286 from '../../assets/sky/dso/PGC088608.jpg';
import dsoImage287 from '../../assets/sky/dso/UGC05373.jpg';
import dsoImage288 from '../../assets/sky/dso/UGC05470.jpg';

export { gaiaAtlasImage };

export const dsoImageAssets: Readonly<Record<string, number>> = {
  B033: dsoImage000,
  C009: dsoImage001,
  C014: dsoImage002,
  C041: dsoImage003,
  C099: dsoImage004,
  Cl399: dsoImage005,
  'ESO056-115': dsoImage006,
  'ESO097-013': dsoImage007,
  'ESO270-017': dsoImage008,
  'ESO351-030': dsoImage009,
  'ESO356-004': dsoImage010,
  HCG079: dsoImage011,
  HCG092: dsoImage012,
  IC0342: dsoImage013,
  IC0348: dsoImage014,
  IC0349: dsoImage015,
  IC0405: dsoImage016,
  IC0434: dsoImage017,
  IC0443: dsoImage018,
  IC1613: dsoImage019,
  IC2220: dsoImage020,
  IC2391: dsoImage021,
  'IC2431 NED02': dsoImage022,
  IC2574: dsoImage023,
  IC2602: dsoImage024,
  IC2944: dsoImage025,
  IC4604: dsoImage026,
  IC4703: dsoImage027,
  IC4715: dsoImage028,
  IC4725: dsoImage029,
  IC5070: dsoImage030,
  IC5146: dsoImage031,
  M040: dsoImage032,
  Mel022: dsoImage033,
  Mel111: dsoImage034,
  NGC0040: dsoImage035,
  NGC0055: dsoImage036,
  NGC0104: dsoImage037,
  NGC0147: dsoImage038,
  NGC0185: dsoImage039,
  NGC0188: dsoImage040,
  NGC0205: dsoImage041,
  NGC0221: dsoImage042,
  NGC0224: dsoImage043,
  NGC0246: dsoImage044,
  NGC0247: dsoImage045,
  NGC0253: dsoImage046,
  NGC0292: dsoImage047,
  NGC0300: dsoImage048,
  NGC0362: dsoImage049,
  NGC0457: dsoImage050,
  NGC0559: dsoImage051,
  NGC0581: dsoImage052,
  NGC0598: dsoImage053,
  NGC0628: dsoImage054,
  NGC0650: dsoImage055,
  NGC0663: dsoImage056,
  NGC0752: dsoImage057,
  NGC0869: dsoImage058,
  NGC0884: dsoImage059,
  NGC0891: dsoImage060,
  NGC1039: dsoImage061,
  NGC1049: dsoImage062,
  NGC1068: dsoImage063,
  NGC1097: dsoImage064,
  NGC1261: dsoImage065,
  NGC1275: dsoImage066,
  NGC1316: dsoImage067,
  NGC1317: dsoImage068,
  NGC1432: dsoImage069,
  NGC1435: dsoImage070,
  NGC1499: dsoImage071,
  NGC1555: dsoImage072,
  NGC1851: dsoImage073,
  NGC1904: dsoImage074,
  NGC1909: dsoImage075,
  NGC1912: dsoImage076,
  NGC1952: dsoImage077,
  NGC1960: dsoImage078,
  NGC1976: dsoImage079,
  NGC1977: dsoImage080,
  NGC1980: dsoImage081,
  NGC1981: dsoImage082,
  NGC1982: dsoImage083,
  NGC2068: dsoImage084,
  NGC2070: dsoImage085,
  NGC2099: dsoImage086,
  NGC2168: dsoImage087,
  NGC2174: dsoImage088,
  NGC2237: dsoImage089,
  NGC2238: dsoImage090,
  NGC2239: dsoImage091,
  NGC2246: dsoImage092,
  NGC2261: dsoImage093,
  NGC2264: dsoImage094,
  NGC2287: dsoImage095,
  NGC2301: dsoImage096,
  NGC2323: dsoImage097,
  NGC2360: dsoImage098,
  NGC2362: dsoImage099,
  NGC2392: dsoImage100,
  NGC2403: dsoImage101,
  NGC2419: dsoImage102,
  NGC2422: dsoImage103,
  NGC2437: dsoImage104,
  NGC2447: dsoImage105,
  NGC2477: dsoImage106,
  NGC2506: dsoImage107,
  NGC2516: dsoImage108,
  NGC2537: dsoImage109,
  NGC2548: dsoImage110,
  NGC2573: dsoImage111,
  NGC2632: dsoImage112,
  NGC2682: dsoImage113,
  NGC2685: dsoImage114,
  NGC2736: dsoImage115,
  NGC2775: dsoImage116,
  NGC2867: dsoImage117,
  NGC3031: dsoImage118,
  NGC3034: dsoImage119,
  NGC3115: dsoImage120,
  NGC3132: dsoImage121,
  NGC3172: dsoImage122,
  NGC3195: dsoImage123,
  NGC3201: dsoImage124,
  NGC3242: dsoImage125,
  NGC3351: dsoImage126,
  NGC3368: dsoImage127,
  NGC3372: dsoImage128,
  NGC3379: dsoImage129,
  NGC3532: dsoImage130,
  NGC3556: dsoImage131,
  NGC3561: dsoImage132,
  NGC3587: dsoImage133,
  NGC3623: dsoImage134,
  NGC3626: dsoImage135,
  NGC3627: dsoImage136,
  NGC3766: dsoImage137,
  NGC3918: dsoImage138,
  NGC3928: dsoImage139,
  NGC3992: dsoImage140,
  NGC4038: dsoImage141,
  NGC4039: dsoImage142,
  NGC4192: dsoImage143,
  NGC4194: dsoImage144,
  NGC4236: dsoImage145,
  NGC4244: dsoImage146,
  NGC4254: dsoImage147,
  NGC4258: dsoImage148,
  NGC4303: dsoImage149,
  NGC4321: dsoImage150,
  NGC4372: dsoImage151,
  NGC4374: dsoImage152,
  NGC4382: dsoImage153,
  NGC4406: dsoImage154,
  NGC4435: dsoImage155,
  NGC4438: dsoImage156,
  NGC4449: dsoImage157,
  NGC4472: dsoImage158,
  NGC4486: dsoImage159,
  NGC4501: dsoImage160,
  NGC4548: dsoImage161,
  NGC4552: dsoImage162,
  NGC4559: dsoImage163,
  NGC4565: dsoImage164,
  NGC4567: dsoImage165,
  NGC4568: dsoImage166,
  NGC4569: dsoImage167,
  NGC4579: dsoImage168,
  NGC4590: dsoImage169,
  NGC4594: dsoImage170,
  NGC4609: dsoImage171,
  NGC4621: dsoImage172,
  NGC4631: dsoImage173,
  NGC4649: dsoImage174,
  NGC4651: dsoImage175,
  NGC4676: dsoImage176,
  NGC4697: dsoImage177,
  NGC4736: dsoImage178,
  NGC4755: dsoImage179,
  NGC4826: dsoImage180,
  NGC4833: dsoImage181,
  NGC4889: dsoImage182,
  NGC4945: dsoImage183,
  NGC4990: dsoImage184,
  NGC5005: dsoImage185,
  NGC5024: dsoImage186,
  NGC5055: dsoImage187,
  NGC5128: dsoImage188,
  NGC5139: dsoImage189,
  NGC5194: dsoImage190,
  NGC5236: dsoImage191,
  NGC5248: dsoImage192,
  NGC5272: dsoImage193,
  NGC5286: dsoImage194,
  NGC5457: dsoImage195,
  NGC5694: dsoImage196,
  NGC5823: dsoImage197,
  NGC5904: dsoImage198,
  NGC6025: dsoImage199,
  NGC6087: dsoImage200,
  NGC6093: dsoImage201,
  NGC6101: dsoImage202,
  NGC6121: dsoImage203,
  NGC6124: dsoImage204,
  NGC6171: dsoImage205,
  NGC6188: dsoImage206,
  NGC6193: dsoImage207,
  NGC6205: dsoImage208,
  NGC6218: dsoImage209,
  NGC6231: dsoImage210,
  NGC6254: dsoImage211,
  NGC6266: dsoImage212,
  NGC6273: dsoImage213,
  NGC6302: dsoImage214,
  NGC6309: dsoImage215,
  NGC6333: dsoImage216,
  NGC6341: dsoImage217,
  NGC6352: dsoImage218,
  NGC6357: dsoImage219,
  NGC6369: dsoImage220,
  NGC6397: dsoImage221,
  NGC6402: dsoImage222,
  NGC6405: dsoImage223,
  NGC6445: dsoImage224,
  NGC6475: dsoImage225,
  NGC6494: dsoImage226,
  NGC6514: dsoImage227,
  NGC6523: dsoImage228,
  NGC6531: dsoImage229,
  NGC6537: dsoImage230,
  NGC6541: dsoImage231,
  NGC6543: dsoImage232,
  NGC6611: dsoImage233,
  NGC6613: dsoImage234,
  NGC6618: dsoImage235,
  NGC6626: dsoImage236,
  NGC6637: dsoImage237,
  NGC6656: dsoImage238,
  NGC6681: dsoImage239,
  NGC6694: dsoImage240,
  NGC6705: dsoImage241,
  NGC6715: dsoImage242,
  NGC6720: dsoImage243,
  NGC6729: dsoImage244,
  NGC6741: dsoImage245,
  NGC6744: dsoImage246,
  NGC6752: dsoImage247,
  NGC6779: dsoImage248,
  NGC6809: dsoImage249,
  NGC6818: dsoImage250,
  NGC6819: dsoImage251,
  NGC6822: dsoImage252,
  NGC6826: dsoImage253,
  NGC6838: dsoImage254,
  NGC6853: dsoImage255,
  NGC6864: dsoImage256,
  NGC6882: dsoImage257,
  NGC6888: dsoImage258,
  NGC6905: dsoImage259,
  NGC6913: dsoImage260,
  NGC6934: dsoImage261,
  NGC6946: dsoImage262,
  NGC6960: dsoImage263,
  NGC6981: dsoImage264,
  NGC6992: dsoImage265,
  NGC6994: dsoImage266,
  NGC6995: dsoImage267,
  NGC7000: dsoImage268,
  NGC7006: dsoImage269,
  NGC7009: dsoImage270,
  NGC7023: dsoImage271,
  NGC7078: dsoImage272,
  NGC7089: dsoImage273,
  NGC7092: dsoImage274,
  NGC7099: dsoImage275,
  NGC7243: dsoImage276,
  NGC7293: dsoImage277,
  NGC7331: dsoImage278,
  NGC7479: dsoImage279,
  NGC7635: dsoImage280,
  NGC7654: dsoImage281,
  NGC7662: dsoImage282,
  NGC7814: dsoImage283,
  PGC000143: dsoImage284,
  PGC029653: dsoImage285,
  PGC088608: dsoImage286,
  UGC05373: dsoImage287,
  UGC05470: dsoImage288,
};
